# Generated by Django 4.0.4 on 2022-05-05 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
